apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api-swear
  name: api-swear
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-swear
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: api-swear
    spec:
      containers:
      - image: api-swear
        imagePullPolicy: ""
        name: swear-api-1
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
