apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api-name
  name: api-name
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-name
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: api-name
    spec:
      containers:
      - image: api-name
        imagePullPolicy: ""
        name: name-api-1
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
