apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db-mongo
  name: db-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db-mongo
    spec:
      containers:
      - image: mongo
        imagePullPolicy: ""
        name: dam
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb
status: {}
