apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db-sql
  name: db-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-sql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db-sql
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: '@Schlafenhase2021'
        image: mcr.microsoft.com/mssql/server
        imagePullPolicy: ""
        name: dadb
        ports:
        - containerPort: 1433
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mssql
        persistentVolumeClaim:
          claimName: mssql
status: {}
