apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: restapi-lb
  name: restapi-lb
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 80
  selector:
    io.kompose.service: restapi-lb
status:
  loadBalancer: {}
