apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: restapi
  name: restapi
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 80
  selector:
    io.kompose.service: restapi
status:
  loadBalancer: {}
