apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web-2
  name: web-2
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 80
  selector:
    io.kompose.service: web-2
status:
  loadBalancer: {}
